[phases.setup]
nixPkgs = ["php82", "nodejs"]

[phases.install]
cmds = [
  "php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\"",
  "php composer-setup.php",
  "php -r \"unlink('composer-setup.php');\"",
  "php composer.phar install --ignore-platform-reqs --no-dev --optimize-autoloader",
  "npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

# Мы просто удалили секцию [start]. 
# Без неё Nixpacks автоматически запустит встроенный Nginx + PHP-FPM, идеально настроенный под Laravel!